# Generated by Django 2.2.1 on 2019-08-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
