# Generated by Django 2.2.1 on 2019-08-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_profilehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilehistory',
            old_name='history',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='username',
            field=models.CharField(default='username', max_length=30),
        ),
    ]
