# Generated by Django 2.2.1 on 2019-08-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20190828_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
